export const API_URL = `${process.env.API_ORIGIN}/api/weblarek`;
export const CDN_URL = `${process.env.API_ORIGIN}/content/weblarek`;

export const settings = {
  page: `.page`,
  productApi: `/product`,
  mainGallery: `.gallery`,
  galleryItem: `.gallery__item`,
  modalContainer: `#modal-container`,
  modal: `.modal`,
  modalContainerClass: `.modal__container`,
  modalContent: `.modal__content`,
  modalActiveClass: `modal_active`,
  modalCloseButton: `.modal__close`,
  modalPreview: `.card_full`,
  headerBasketButton: `.header__basket`,
  headerBasketCounterSpan: `.header__basket-counter`,
  modalBasket: `.basket`,
  basketItem: `.basket__item`,
  basketList: `.basket__list`,
  basketItemIndex: `.basket__item-index`,
  basketPrice: `.basket__price`,
  basketItemDelete: `.basket__item-delete`,
  basketButton: `.basket__button`,
  templateCard: `#card-catalog`,
  categorySelector: `.card__category`,
  titleSelector: `.card__title`,
  imageSelector: `.card__image`,
  priceSelector: `.card__price`, 
  textSelector: `.card__text`,
  buttonSelector: `.card__button`,
  templateSuccess: `#success`,
  templateCardPreview: `#card-preview`,
  templateCardBasket: `#card-basket`,
  templateBasket: `#basket`,
  templateOrder: `#order`,
  templateContacts: `#contacts`,
  // modalContainerSuccess: `#modal-container-success`,
  // modalContainerContact: `#modal-container-contact`,
  // modalContainerPayment: `#modal-container-payment`,
  // modalContainerBasket: `#modal-container-basket`,
  // modalContainerPreview: `#modal-container-preview`,
  // view: {
  //   gallery: `gallery`, 
  //   preview: `preview`, 
  //   basket: `basket`
  // },
};


